INCIDENT_TYPES={
    "AUTHENTICATION":"Authentication",
    "BRUTE_FORCE":"Brute Force",
    "EXECUTION":"Execution",
    "PERSISTENCE":"Persistence",
    "PRIVILEGE_ESCALATION":"Privilege Escalation",
    "DEFENSE_EVASION":"Defense Evasion",
    "CREDENTIAL_ACCESS":"Credential Access",
    "DISCOVERY":"Discovery",
    "LATERAL_MOVEMENT":"Lateral Movement",
    "COMMAND_AND_CONTROL":"Command and Control",
    "EXFILTRATION":"Exfiltration",
    "IMPACT":"Impact",
    "MALWARE":"Malware",
    "NETWORK_ATTACK":"Network Attack",
    "FILE_INTEGRITY":"File Integrity",
    "POLICY_VIOLATION":"Policy Violation",
    "SYSTEM":"System",
    "OTHER":"Other"}
MITRE_MAPPING={
    "Initial Access":INCIDENT_TYPES["AUTHENTICATION"],
    "Execution":INCIDENT_TYPES["EXECUTION"],
    "Persistence":INCIDENT_TYPES["PERSISTENCE"],
    "Privilege Escalation":INCIDENT_TYPES["PRIVILEGE_ESCALATION"],
    "Defense Evasion":INCIDENT_TYPES["DEFENSE_EVASION"],
    "Credential Access":INCIDENT_TYPES["CREDENTIAL_ACCESS"],
    "Discovery":INCIDENT_TYPES["DISCOVERY"],
    "Lateral Movement":INCIDENT_TYPES["LATERAL_MOVEMENT"],
    "Collection":INCIDENT_TYPES["CREDENTIAL_ACCESS"],
    "Command and Control":INCIDENT_TYPES["COMMAND_AND_CONTROL"],
    "Exfiltration":INCIDENT_TYPES["EXFILTRATION"],
    "Impact":INCIDENT_TYPES["IMPACT"]}
TECHNIQUE_MAPPING={
    "Brute Force":INCIDENT_TYPES["BRUTE_FORCE"],
    "Password Guessing":INCIDENT_TYPES["BRUTE_FORCE"],
    "Valid Accounts":INCIDENT_TYPES["AUTHENTICATION"],
    "OS Credential Dumping":INCIDENT_TYPES["CREDENTIAL_ACCESS"],
    "Credentials from Password Stores":INCIDENT_TYPES["CREDENTIAL_ACCESS"],
    "Input Capture":INCIDENT_TYPES["CREDENTIAL_ACCESS"],
    "PowerShell":INCIDENT_TYPES["EXECUTION"],
    "Command and Scripting Interpreter":INCIDENT_TYPES["EXECUTION"],
    "User Execution":INCIDENT_TYPES["EXECUTION"],
    "Scheduled Task/Job":INCIDENT_TYPES["PERSISTENCE"],
    "Create or Modify System Process":INCIDENT_TYPES["PERSISTENCE"],
    "Boot or Logon Autostart Execution":INCIDENT_TYPES["PERSISTENCE"],
    "Impair Defenses":INCIDENT_TYPES["DEFENSE_EVASION"],
    "Indicator Removal":INCIDENT_TYPES["DEFENSE_EVASION"],
    "System Information Discovery":INCIDENT_TYPES["DISCOVERY"],
    "Process Discovery":INCIDENT_TYPES["DISCOVERY"],
    "Network Service Scanning":INCIDENT_TYPES["DISCOVERY"],
    "Remote Services":INCIDENT_TYPES["LATERAL_MOVEMENT"],
    "Remote Desktop Protocol":INCIDENT_TYPES["LATERAL_MOVEMENT"],
    "Ingress Tool Transfer":INCIDENT_TYPES["COMMAND_AND_CONTROL"],
    "Application Layer Protocol":INCIDENT_TYPES["COMMAND_AND_CONTROL"],
    "Data Encrypted for Impact":INCIDENT_TYPES["IMPACT"]
}

GROUP_MAPPING={
    "authentication_failed":INCIDENT_TYPES["BRUTE_FORCE"],
    "authentication_success":INCIDENT_TYPES["AUTHENTICATION"],
    "access_control":INCIDENT_TYPES["AUTHENTICATION"],
    "pam":INCIDENT_TYPES["AUTHENTICATION"],
    "sshd":INCIDENT_TYPES["AUTHENTICATION"],
    "powershell":INCIDENT_TYPES["EXECUTION"],
    "process_monitor":INCIDENT_TYPES["EXECUTION"],
    "sysmon_event1":INCIDENT_TYPES["EXECUTION"],
    "scheduled_task":INCIDENT_TYPES["PERSISTENCE"],
    "service":INCIDENT_TYPES["PERSISTENCE"],
    "registry":INCIDENT_TYPES["PERSISTENCE"],
    "sudo":INCIDENT_TYPES["PRIVILEGE_ESCALATION"],
    "uac":INCIDENT_TYPES["PRIVILEGE_ESCALATION"],
    "lsass":INCIDENT_TYPES["CREDENTIAL_ACCESS"],
    "mimikatz":INCIDENT_TYPES["CREDENTIAL_ACCESS"],
    "malware":INCIDENT_TYPES["MALWARE"],
    "virus":INCIDENT_TYPES["MALWARE"],
    "rootcheck":INCIDENT_TYPES["MALWARE"],
    "suricata":INCIDENT_TYPES["NETWORK_ATTACK"],
    "firewall":INCIDENT_TYPES["NETWORK_ATTACK"],
    "ids":INCIDENT_TYPES["NETWORK_ATTACK"],
    "syscheck":INCIDENT_TYPES["FILE_INTEGRITY"],
    "fim":INCIDENT_TYPES["FILE_INTEGRITY"],
    "compliance":INCIDENT_TYPES["POLICY_VIOLATION"]
}

DECODER_MAPPING={
    "sshd":INCIDENT_TYPES["AUTHENTICATION"],
    "powershell":INCIDENT_TYPES["EXECUTION"],
    "sysmon":INCIDENT_TYPES["EXECUTION"],
    "auditd":INCIDENT_TYPES["SYSTEM"],
    "sudo":INCIDENT_TYPES["PRIVILEGE_ESCALATION"],
    "clamav":INCIDENT_TYPES["MALWARE"],
    "suricata":INCIDENT_TYPES["NETWORK_ATTACK"]
}

DESCRIPTION_KEYWORDS={
    "failed password":INCIDENT_TYPES["BRUTE_FORCE"],
    "authentication failure":INCIDENT_TYPES["BRUTE_FORCE"],
    "too many authentication failures":INCIDENT_TYPES["BRUTE_FORCE"],
    "brute force":INCIDENT_TYPES["BRUTE_FORCE"],
    "powershell":INCIDENT_TYPES["EXECUTION"],
    "encodedcommand":INCIDENT_TYPES["EXECUTION"],
    "base64":INCIDENT_TYPES["EXECUTION"],
    "cmd.exe":INCIDENT_TYPES["EXECUTION"],
    "mimikatz":INCIDENT_TYPES["CREDENTIAL_ACCESS"],
    "lsass":INCIDENT_TYPES["CREDENTIAL_ACCESS"],
    "scheduled task":INCIDENT_TYPES["PERSISTENCE"],
    "new service":INCIDENT_TYPES["PERSISTENCE"],
    "disable security":INCIDENT_TYPES["DEFENSE_EVASION"],
    "clear logs":INCIDENT_TYPES["DEFENSE_EVASION"],
    "ransomware":INCIDENT_TYPES["IMPACT"],
    "encrypt":INCIDENT_TYPES["IMPACT"],
    "trojan":INCIDENT_TYPES["MALWARE"],
    "backdoor":INCIDENT_TYPES["MALWARE"],
    "port scan":INCIDENT_TYPES["NETWORK_ATTACK"],
    "nmap":INCIDENT_TYPES["NETWORK_ATTACK"],
    "connection refused":INCIDENT_TYPES["NETWORK_ATTACK"]
}